--
-- PostgreSQL database cluster dump
--

-- Started on 2023-12-18 23:57:57

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-18 23:57:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2023-12-18 23:57:57

--
-- PostgreSQL database dump complete
--

--
-- Database "CoffeeHouse" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-18 23:57:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4825 (class 1262 OID 24576)
-- Name: CoffeeHouse; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "CoffeeHouse" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


\connect "CoffeeHouse"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 852 (class 1247 OID 32889)
-- Name: dishes; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.dishes AS ENUM (
    'Ratatouille',
    'CoqAuVin',
    'Raclette',
    'Macaron',
    'BoeufBourguignon',
    'MilleFeuille',
    'Bouillabaisse',
    'Baguette',
    'Escargot',
    'Champagne',
    'OnionSoup',
    'QuicheLorraine',
    'GratinDauphinois',
    'Souffle',
    'ConfitDeCanard',
    'Madeleines',
    'MoulesMarinieres',
    'HachisParmentier',
    'Crepes',
    'SaladeNicoise',
    'CheeseFondue',
    'Croissant',
    'FrogsLegs',
    'BavarianCream',
    'Omelette',
    'TarteTatin',
    'Chateaubriand',
    'FoieGras',
    'Brioche',
    'Brandade',
    'Cassoulet',
    'Eclair',
    'JambonBeurre',
    'Pissaladiere'
);


--
-- TOC entry 846 (class 1247 OID 32787)
-- Name: employee_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.employee_role AS ENUM (
    'Administrator',
    'Chef',
    'Waiter'
);


--
-- TOC entry 849 (class 1247 OID 32806)
-- Name: employee_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.employee_status AS ENUM (
    'Hired',
    'Fired'
);


--
-- TOC entry 855 (class 1247 OID 32958)
-- Name: order_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.order_status AS ENUM (
    'Accepted',
    'Cooking',
    'Ready',
    'Paid'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 33234)
-- Name: Account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Account" (
    "Id" integer NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 33233)
-- Name: Account_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Account" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Account_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 33250)
-- Name: Employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Employee" (
    "Id" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Patronymic" text,
    "Role" text NOT NULL,
    "Status" text NOT NULL,
    "AccountId" integer NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 33249)
-- Name: Employee_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Employee" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employee_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 33242)
-- Name: Order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Order" (
    "Id" integer NOT NULL,
    "Table" integer NOT NULL,
    "CustomerAmount" integer NOT NULL,
    "Dishes" text[] NOT NULL,
    "Status" text NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 33241)
-- Name: Order_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Order" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Order_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 33228)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 4815 (class 0 OID 33234)
-- Dependencies: 217
-- Data for Name: Account; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Account" ("Id", "Login", "Password") FROM stdin;
1	admin	admin
2	waiter	waiter
3	chef	chef
\.


--
-- TOC entry 4819 (class 0 OID 33250)
-- Dependencies: 221
-- Data for Name: Employee; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Employee" ("Id", "FirstName", "LastName", "Patronymic", "Role", "Status", "AccountId") FROM stdin;
2	Anton	Baskakov	Sergeevic	Waiter	Hired	2
3	Svetlana	Baskakova	Nikolaevna	Chef	Hired	3
1	Daniil	Baskakov	Sergeevic	Administrator	Hired	1
\.


--
-- TOC entry 4817 (class 0 OID 33242)
-- Dependencies: 219
-- Data for Name: Order; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Order" ("Id", "Table", "CustomerAmount", "Dishes", "Status") FROM stdin;
6	2	1	{Baguette,Brandade,CoqAuVin,HachisParmentier}	Paid
8	0	0	{QuicheLorraine}	Accepted
9	3	1	{Baguette,Souffle}	Paid
10	10	4	{Baguette,MilleFeuille,Ratatouille}	Accepted
3	1	2	{Baguette,Baguette,Baguette}	Accepted
2	5	6	{Souffle,FrogsLegs,TarteTatin}	Paid
11	2	2	{Baguette}	Accepted
1	5	12	{Macaron,Pissaladiere,OnionSoup,Eclair}	Accepted
12	12	12	{Brioche,MoulesMarinieres}	Paid
4	2	1	{Baguette,Baguette,Baguette,Baguette,Baguette}	Cooking
7	0	0	{Baguette,Brioche}	Ready
5	2	1	{Baguette,Baguette}	Ready
\.


--
-- TOC entry 4813 (class 0 OID 33228)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20231218155922_Initial	6.0.25
\.


--
-- TOC entry 4826 (class 0 OID 0)
-- Dependencies: 216
-- Name: Account_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Account_Id_seq"', 3, true);


--
-- TOC entry 4827 (class 0 OID 0)
-- Dependencies: 220
-- Name: Employee_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Employee_Id_seq"', 3, true);


--
-- TOC entry 4828 (class 0 OID 0)
-- Dependencies: 218
-- Name: Order_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Order_Id_seq"', 10, true);


--
-- TOC entry 4663 (class 2606 OID 33240)
-- Name: Account PK_Account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "PK_Account" PRIMARY KEY ("Id");


--
-- TOC entry 4668 (class 2606 OID 33256)
-- Name: Employee PK_Employee; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "PK_Employee" PRIMARY KEY ("Id");


--
-- TOC entry 4665 (class 2606 OID 33248)
-- Name: Order PK_Order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "PK_Order" PRIMARY KEY ("Id");


--
-- TOC entry 4661 (class 2606 OID 33232)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4666 (class 1259 OID 33262)
-- Name: IX_Employee_AccountId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Employee_AccountId" ON public."Employee" USING btree ("AccountId");


--
-- TOC entry 4669 (class 2606 OID 33257)
-- Name: Employee FK_Employee_Account_AccountId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "FK_Employee_Account_AccountId" FOREIGN KEY ("AccountId") REFERENCES public."Account"("Id") ON DELETE CASCADE;


-- Completed on 2023-12-18 23:57:57

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-18 23:57:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16384)
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- TOC entry 4778 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


-- Completed on 2023-12-18 23:57:57

--
-- PostgreSQL database dump complete
--

--
-- Database "todo" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-12-18 23:57:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4795 (class 1262 OID 16398)
-- Name: todo; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE todo WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


\connect todo

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message (
    id integer NOT NULL,
    message character varying(255),
    tag character varying(255)
);


--
-- TOC entry 216 (class 1259 OID 16406)
-- Name: message_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.message_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 217 (class 1259 OID 16407)
-- Name: task; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task (
    id integer NOT NULL,
    description character varying(255),
    label character varying(255),
    type character varying(255)
);


--
-- TOC entry 218 (class 1259 OID 16414)
-- Name: task_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.task_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 4786 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: message; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.message (id, message, tag) FROM stdin;
1	pisyat dva	ny lan
2	pisyat dva	ny lan
52	pisyat dva	ny lan
53		
54		
55		
\.


--
-- TOC entry 4788 (class 0 OID 16407)
-- Dependencies: 217
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.task (id, description, label, type) FROM stdin;
302	ThugLife	ThugLife	ThugLife
352			
\.


--
-- TOC entry 4796 (class 0 OID 0)
-- Dependencies: 216
-- Name: message_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.message_seq', 101, true);


--
-- TOC entry 4797 (class 0 OID 0)
-- Dependencies: 218
-- Name: task_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.task_seq', 401, true);


--
-- TOC entry 4640 (class 2606 OID 16405)
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- TOC entry 4642 (class 2606 OID 16413)
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


-- Completed on 2023-12-18 23:57:58

--
-- PostgreSQL database dump complete
--

-- Completed on 2023-12-18 23:57:58

--
-- PostgreSQL database cluster dump complete
--

